lecture4/airline/airline/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flights/", include("flights.urls")),
    path("users/", include("users.urls")),
]

lecture4/airline/flights/urls.py
from django.urls import path
from . import views

app_name = "flights"
urlpatterns = [ 
  path('', views.index, name='index'),
  path("<int:flight_id>", views.flight, name="flight"),
  path("<int:flight_id>/book", views.book, name="book")
]

lecture4/airline/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [ 
  path('', views.index, name='index'),
  path("login", views.login_view, name="login"),
  path("logout", views.logout_view, name="logout"),
]

lecture4/airline/flights/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
  code = models.CharField(max_length=3)
  city = models.CharField(max_length=64)

  def __str__(self):
    return f"{self.city} ({self.code})"
class Flight(models.Model):
  origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
  destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
  duration = models.IntegerField()

  def __str__(self):
    return f"{self.id}: {self.origin} -> {self.destination} in {self.duration} mins"

class Passenger(models.Model):
  first = models.CharField(max_length=64)
  last = models.CharField(max_length=64)
  flights = models.ManyToManyField(Flight, blank=True, related_name="passengers")

  def __str__(self):
    return f"{self.first} {self.last}"

lecture4/airline/users/models.py
from django.db import models

# Create your models here.

lecture4/airline/flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Flight, Passenger

# Create your views here.
def index(request):
  return render(request, 'flights/index.html', {'flights': Flight.objects.all()})

def flight(request, flight_id):
  flight = Flight.objects.get(pk=flight_id)
  return render(request, 'flights/flight.html', {
    'flight': flight,
    "passengers": flight.passengers.all(),
    "non_passengers": Passenger.objects.exclude(flights=flight).all()
    })

def book(request, flight_id):
  if request.method == "POST":
    flight = Flight.objects.get(pk=flight_id)
    passenger = Passenger.objects.get(pk=int(request.POST["passenger"]))
    passenger.flights.add(flight)
    return HttpResponseRedirect(reverse("flights:flight", args=[flight_id]))

lecture4/airline/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# Create your views here.
def index(request):
  if not request.user.is_authenticated:
    return HttpResponseRedirect(reverse("users:login"))
  return render(request, "users/user.html")

def login_view(request):
  if request.method == "POST":
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
      login(request, user)
      return HttpResponseRedirect(reverse("users:index"))
    else:
      return render(request, "users/login.html", {
        "message": "Invalid credentials."
      })
  return render(request, "users/login.html")

def logout_view(request):
  logout(request)
  return render(request, "users/login.html", {
    "message": "You have been logged out."
  })

lecture4/airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block body %}
  <h1>Flight {{ flight.id }}</h1>
  <ul>
    <li>Origin: {{ flight.origin }}</li>
    <li>Destination: {{ flight.destination }}</li>
    <li>Duration: {{ flight.duration }} mins</li>
  </ul>
  <h2>Passengers</h2>
  <ul>
    {% for passenger in passengers %}
      <li>{{ passenger }}</li>
      {% empty %}
        <li>No passengers</li>
    {% endfor %}
  </ul>
  <h2>Add Passenger</h2>
  <form action="{% url 'flights:book' flight.id %}" method="post">
    {% csrf_token %}
    <select name="passenger">
      {% for passenger in non_passengers %}
        <option value="{{ passenger.id }}">{{ passenger }}</option>
        {% empty %}
          <option disabled value="" selected>No passengers left</option>
      {% endfor %}
    </select>
    {% if non_passengers %}
      <input type="submit" value="submit">
    {% endif %}
  </form>

  <a href="{% url 'flights:index' %}">Back to flights</a>
{% endblock %}

lecture4/airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}

{% block body %}
  <h1>Flights</h1>
  <ul>
    {% for flight in flights %}
      <li>
        <a href="{% url 'flights:flight' flight.id %}">
          Flight {{ flight.id }}: {{ flight.origin }} -> {{ flight.destination }} in {{ flight.duration }} mins</li>
        </a>
    {% endfor %}
  </ul>
{% endblock %}

lecture4/airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Flights</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>

lecture4/airline/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Users</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>

lecture4/airline/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
  {% if message %}
    <div>{{ message }}</div>
  {% endif %}
  <h1>Login</h1>
  <form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Login">
  </form>
{% endblock %}

lecture4/airline/users/templates/users/user.html
{% extends "users/layout.html" %}

{% block body %}
  <h1>Welcome {{ user.first_name }}</h1>
  <ul>
    <li>Username: {{ user.username }}</li>
    <li>Email: {{ user.email }}</li>
  </ul>
  <a href="{% url 'users:logout' %}">Logout</a>
{% endblock %}