lecture3/CS50_project/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture3/CS50_project/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("tasks/", include("tasks.urls")),
]

lecture3/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add, name="add"),
]

lecture3/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse

class NewTaskForm(forms.Form):
  task = forms.CharField(label="New Task")
  priority = forms.IntegerField(label="Priority", min_value=1, max_value=3)
# Create your views here.
def index(request):
  if "tasks" not in request.session:
    request.session["tasks"] = []
  return render(request, "tasks/index.html", {
    "tasks": request.session["tasks"]
  })

def add(request):
  if request.method == "POST":
    form = NewTaskForm(request.POST)
    if form.is_valid():
      task = form.cleaned_data["task"]
      request.session["tasks"] += [task]
      return HttpResponseRedirect(reverse("tasks:index"))
    else:
      return render(request, "tasks/add.html", {
        "form": form
      })
  return render(request, "tasks/add.html", {
    "form": NewTaskForm()
  })

lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}
{% block content %}
  <h1>Add task</h1>
  <form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Add">
  </form>
  <a href="{% url 'tasks:index' %}">View tasks</a>
{% endblock %}

lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% block content %}
  <ul>
    {% for task in tasks %}
      <li>{{ task }}</li>
      {% empty %}
      <li>No tasks yet.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tasks</title>
</head>
<body>
  <h1>Tasks</h1>
  {% block content %}
  {% endblock %}
</body>
</html>